# Generated by Django 3.1.7 on 2021-03-17 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_auto_20210317_1316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('-created_at',), 'verbose_name': 'Invoice', 'verbose_name_plural': 'Invoices'},
        ),
    ]
